package com.greennetwork.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Name
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Age
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Name
     *
     * @return the value of user.Name
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Name
     *
     * @param name the value for user.Name
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Age
     *
     * @return the value of user.Age
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Age
     *
     * @param age the value for user.Age
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbg.generated Tue Mar 21 19:27:17 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}